name: CD

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: self-hosted # Gunakan self-hosted runner

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install dependencies
              run: |
                  cd ~/ptba.id
                  git fetch origin main
                  git reset --hard origin/main
                  npm install

            - name: Restart application
              run: |
                  pm2 restart ptba.id
